import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Company() {
return (
    <div className={styles.container}>
        <Head>
            <title>Kik token</title>
            <meta name="description" content="Generated by create next app" />
            <link rel = "icon" href = "https://ikalas.com/logo.png" type = "image/x-icon" />
        </Head>
        <main className={styles.main}>
            <h1 className={styles.title}>
                The Ikalas Corporation
            </h1>
        </main>
    </div>
    )
}
