import { imageConfigDefault } from 'next/dist/shared/lib/image-config'
import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kik token</title>
        <meta name="description" content="Generated by create next app" />
        <link rel = "icon" href = "https://ikalas.com/logo.png" type = "image/x-icon" />
      </Head>

      <main className={styles.main}>
        <div className={styles.mainTitle}>
          <h1 className={styles.title}>
          KiK Token
        </h1>
        <Image className={styles.imgHome} src="/images/logo.png" alt="Kik" width={90} height={90}/>
        </div>
        
        <h2 className={styles.slogan}>
          Avoid complexity,<br/>
          welcome simplicity
        </h2>

          <div className={`${styles.card} ${styles.questions}`}>
            <h3>
              What is the Kik token ?
            </h3>
            <p className={styles.textCenter}>Kik is a cryptocurrency used in the platform <a href="https://ikalas.com/app"></a>. The Kik token is fully tradable and allow the owners to get discount and specific
            pivileges on the platform.</p>
          </div>
            
      </main>

    </div>
  )
}
