import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../component/Navbar'
import Login from '../component/Login'
import { useWeb3 } from "@3rdweb/hooks"
import styles from '../styles/Home.module.css'




export default function Swap() {
    const { connectWallet, address, error } = useWeb3();
    return (

        <div className={styles.container}>
            <Head>
                <title>Kik token</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="https://ikalas.com/logo.png" type="image/x-icon" />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Exchange your tokens
                </h1>
                <Login>
                    
                </Login>
            </main>
        </div>
    )
}