import Head from "next/head";
import Script from "next/dist/client/script";


const Header = () => {
  return (
    <Head>
        <title>Kik token</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="images/logo.png"/>

        <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.css" />
        <link rel="stylesheet" href="/assets/css/libs.bundle.css" />
        <link rel="stylesheet" href="/assets/css/theme.bundle.css" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/smooth-scroll/16.1.0/smooth-scroll.min.js"/>
      </Head>
  );
};

export default Header;