


const Header = () => {
  return (
    <header>
        <title>Kik token</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.ico" type="image/x-icon" />

        <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.css" />
        <link rel="stylesheet" href="/assets/css/libs.bundle.css" />
        <link rel="stylesheet" href="/assets/css/theme.bundle.css" />
      </header>
  );
};

export default Header;